// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public final class Airquality {
  private Airquality() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_SensorID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_SensorID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_COLevels_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_COLevels_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_AirQualityData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_AirQualityData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_Thresholds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_Thresholds_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_SuccessStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_SuccessStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020airquality.proto\022\nairquality\"\026\n\010Sensor" +
      "ID\022\n\n\002id\030\001 \001(\t\"\032\n\010COLevels\022\016\n\006levels\030\001 \001" +
      "(\002\"#\n\016AirQualityData\022\021\n\tco_levels\030\001 \001(\002\"" +
      "#\n\nThresholds\022\025\n\rco_thresholds\030\001 \001(\002\" \n\r" +
      "SuccessStatus\022\017\n\007success\030\001 \001(\0102\226\001\n\004AQMS\022" +
      "D\n\024GetCurrentAirQuality\022\024.airquality.Sen" +
      "sorID\032\024.airquality.COLevels\"\000\022H\n\021SetAler" +
      "tThreshold\022\026.airquality.Thresholds\032\031.air" +
      "quality.SuccessStatus\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airquality_SensorID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airquality_SensorID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_SensorID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_airquality_COLevels_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airquality_COLevels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_COLevels_descriptor,
        new java.lang.String[] { "Levels", });
    internal_static_airquality_AirQualityData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airquality_AirQualityData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_AirQualityData_descriptor,
        new java.lang.String[] { "CoLevels", });
    internal_static_airquality_Thresholds_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_airquality_Thresholds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_Thresholds_descriptor,
        new java.lang.String[] { "CoThresholds", });
    internal_static_airquality_SuccessStatus_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_airquality_SuccessStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_SuccessStatus_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
