// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface AirQualityDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.AirQualityData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Define the fields for air quality data
   * Example fields: CO levels, temperature, etc.
   * </pre>
   *
   * <code>float co_levels = 1;</code>
   */
  float getCoLevels();
}
