// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface COLevelsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.COLevels)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float levels = 1;</code>
   */
  float getLevels();
}
