// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface SensorIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.SensorID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
