// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface SuccessStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.SuccessStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
