// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface ThresholdsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.Thresholds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Add more thresholds as needed
   * </pre>
   *
   * <code>float co_thresholds = 1;</code>
   */
  float getCoThresholds();
}
