// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package airquality;

public interface TimeRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.TimeRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_timestamp = 1;</code>
   */
  long getStartTimestamp();

  /**
   * <code>int64 end_timestamp = 2;</code>
   */
  long getEndTimestamp();
}
