// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package alert;

public interface AlertMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.AlertMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Alert message content.
   * </pre>
   *
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <pre>
   * Alert message content.
   * </pre>
   *
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
