// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package alert;

public final class Alert {
  private Alert() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_UnregisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_UnregisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_UnregisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_UnregisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_StreamAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_StreamAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alert_AlertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alert_AlertMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013alert.proto\022\005alert\"-\n\017RegisterRequest\022" +
      "\032\n\022contactInformation\030\001 \001(\t\"#\n\020RegisterR" +
      "esponse\022\017\n\007message\030\001 \001(\t\"/\n\021UnregisterRe" +
      "quest\022\032\n\022contactInformation\030\001 \001(\t\"%\n\022Unr" +
      "egisterResponse\022\017\n\007message\030\001 \001(\t\"1\n\023Stre" +
      "amAlertsRequest\022\032\n\022contactInformation\030\001 " +
      "\001(\t\"\037\n\014AlertMessage\022\017\n\007content\030\001 \001(\t2\367\001\n" +
      "\030AlertNotificationService\022F\n\021RegisterFor" +
      "Alerts\022\026.alert.RegisterRequest\032\027.alert.R" +
      "egisterResponse\"\000\022L\n\023UnregisterForAlerts" +
      "\022\030.alert.UnregisterRequest\032\031.alert.Unreg" +
      "isterResponse\"\000\022E\n\014StreamAlerts\022\032.alert." +
      "StreamAlertsRequest\032\023.alert.AlertMessage" +
      "\"\000(\0010\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alert_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alert_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_RegisterRequest_descriptor,
        new java.lang.String[] { "ContactInformation", });
    internal_static_alert_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alert_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_RegisterResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_alert_UnregisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alert_UnregisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_UnregisterRequest_descriptor,
        new java.lang.String[] { "ContactInformation", });
    internal_static_alert_UnregisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alert_UnregisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_UnregisterResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_alert_StreamAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_alert_StreamAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_StreamAlertsRequest_descriptor,
        new java.lang.String[] { "ContactInformation", });
    internal_static_alert_AlertMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_alert_AlertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alert_AlertMessage_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
