// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package alert;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Success status message confirming registration.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Success status message confirming registration.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
