// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package alert;

public interface StreamAlertsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.StreamAlertsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User contact information.
   * </pre>
   *
   * <code>string contactInformation = 1;</code>
   */
  java.lang.String getContactInformation();
  /**
   * <pre>
   * User contact information.
   * </pre>
   *
   * <code>string contactInformation = 1;</code>
   */
  com.google.protobuf.ByteString
      getContactInformationBytes();
}
