// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface CurrentPhLevelsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.CurrentPhLevels)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float ph = 1;</code>
   */
  float getPh();
}
