// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface SetAlertThresholdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.SetAlertThresholdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float min_ph = 1;</code>
   */
  float getMinPh();

  /**
   * <code>float max_ph = 2;</code>
   */
  float getMaxPh();
}
