// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface SetAlertThresholdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.SetAlertThresholdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
