// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

/**
 * <pre>
 * Message for the request containing pH thresholds.
 * </pre>
 *
 * Protobuf type {@code waterquality.SetAlertThresholdRequest}
 */
public  final class SetAlertThresholdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:waterquality.SetAlertThresholdRequest)
    SetAlertThresholdRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetAlertThresholdRequest.newBuilder() to construct.
  private SetAlertThresholdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetAlertThresholdRequest() {
    minPh_ = 0F;
    maxPh_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetAlertThresholdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            minPh_ = input.readFloat();
            break;
          }
          case 21: {

            maxPh_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return waterquality.Waterquality.internal_static_waterquality_SetAlertThresholdRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return waterquality.Waterquality.internal_static_waterquality_SetAlertThresholdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            waterquality.SetAlertThresholdRequest.class, waterquality.SetAlertThresholdRequest.Builder.class);
  }

  public static final int MIN_PH_FIELD_NUMBER = 1;
  private float minPh_;
  /**
   * <code>float min_ph = 1;</code>
   */
  public float getMinPh() {
    return minPh_;
  }

  public static final int MAX_PH_FIELD_NUMBER = 2;
  private float maxPh_;
  /**
   * <code>float max_ph = 2;</code>
   */
  public float getMaxPh() {
    return maxPh_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (minPh_ != 0F) {
      output.writeFloat(1, minPh_);
    }
    if (maxPh_ != 0F) {
      output.writeFloat(2, maxPh_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (minPh_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, minPh_);
    }
    if (maxPh_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, maxPh_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof waterquality.SetAlertThresholdRequest)) {
      return super.equals(obj);
    }
    waterquality.SetAlertThresholdRequest other = (waterquality.SetAlertThresholdRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getMinPh())
        == java.lang.Float.floatToIntBits(
            other.getMinPh()));
    result = result && (
        java.lang.Float.floatToIntBits(getMaxPh())
        == java.lang.Float.floatToIntBits(
            other.getMaxPh()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_PH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinPh());
    hash = (37 * hash) + MAX_PH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxPh());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static waterquality.SetAlertThresholdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static waterquality.SetAlertThresholdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static waterquality.SetAlertThresholdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static waterquality.SetAlertThresholdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(waterquality.SetAlertThresholdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message for the request containing pH thresholds.
   * </pre>
   *
   * Protobuf type {@code waterquality.SetAlertThresholdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:waterquality.SetAlertThresholdRequest)
      waterquality.SetAlertThresholdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waterquality.Waterquality.internal_static_waterquality_SetAlertThresholdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waterquality.Waterquality.internal_static_waterquality_SetAlertThresholdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              waterquality.SetAlertThresholdRequest.class, waterquality.SetAlertThresholdRequest.Builder.class);
    }

    // Construct using waterquality.SetAlertThresholdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      minPh_ = 0F;

      maxPh_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return waterquality.Waterquality.internal_static_waterquality_SetAlertThresholdRequest_descriptor;
    }

    @java.lang.Override
    public waterquality.SetAlertThresholdRequest getDefaultInstanceForType() {
      return waterquality.SetAlertThresholdRequest.getDefaultInstance();
    }

    @java.lang.Override
    public waterquality.SetAlertThresholdRequest build() {
      waterquality.SetAlertThresholdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public waterquality.SetAlertThresholdRequest buildPartial() {
      waterquality.SetAlertThresholdRequest result = new waterquality.SetAlertThresholdRequest(this);
      result.minPh_ = minPh_;
      result.maxPh_ = maxPh_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof waterquality.SetAlertThresholdRequest) {
        return mergeFrom((waterquality.SetAlertThresholdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(waterquality.SetAlertThresholdRequest other) {
      if (other == waterquality.SetAlertThresholdRequest.getDefaultInstance()) return this;
      if (other.getMinPh() != 0F) {
        setMinPh(other.getMinPh());
      }
      if (other.getMaxPh() != 0F) {
        setMaxPh(other.getMaxPh());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      waterquality.SetAlertThresholdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (waterquality.SetAlertThresholdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float minPh_ ;
    /**
     * <code>float min_ph = 1;</code>
     */
    public float getMinPh() {
      return minPh_;
    }
    /**
     * <code>float min_ph = 1;</code>
     */
    public Builder setMinPh(float value) {
      
      minPh_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float min_ph = 1;</code>
     */
    public Builder clearMinPh() {
      
      minPh_ = 0F;
      onChanged();
      return this;
    }

    private float maxPh_ ;
    /**
     * <code>float max_ph = 2;</code>
     */
    public float getMaxPh() {
      return maxPh_;
    }
    /**
     * <code>float max_ph = 2;</code>
     */
    public Builder setMaxPh(float value) {
      
      maxPh_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float max_ph = 2;</code>
     */
    public Builder clearMaxPh() {
      
      maxPh_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:waterquality.SetAlertThresholdRequest)
  }

  // @@protoc_insertion_point(class_scope:waterquality.SetAlertThresholdRequest)
  private static final waterquality.SetAlertThresholdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new waterquality.SetAlertThresholdRequest();
  }

  public static waterquality.SetAlertThresholdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetAlertThresholdRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetAlertThresholdRequest>() {
    @java.lang.Override
    public SetAlertThresholdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetAlertThresholdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetAlertThresholdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetAlertThresholdRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public waterquality.SetAlertThresholdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

