// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface WaterQualityHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .waterquality.WaterQualityData data = 1;</code>
   */
  java.util.List<waterquality.WaterQualityData> 
      getDataList();
  /**
   * <code>repeated .waterquality.WaterQualityData data = 1;</code>
   */
  waterquality.WaterQualityData getData(int index);
  /**
   * <code>repeated .waterquality.WaterQualityData data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .waterquality.WaterQualityData data = 1;</code>
   */
  java.util.List<? extends waterquality.WaterQualityDataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .waterquality.WaterQualityData data = 1;</code>
   */
  waterquality.WaterQualityDataOrBuilder getDataOrBuilder(
      int index);
}
