// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface WaterQualityDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float ph = 1;</code>
   */
  float getPh();

  /**
   * <code>float turbidity = 2;</code>
   */
  float getTurbidity();

  /**
   * <code>float tds = 3;</code>
   */
  float getTds();

  /**
   * <code>float temperature = 4;</code>
   */
  float getTemperature();
}
