// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface WaterQualityHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_timestamp = 1;</code>
   */
  long getStartTimestamp();

  /**
   * <code>int64 end_timestamp = 2;</code>
   */
  long getEndTimestamp();
}
