// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package waterquality;

public interface WaterQualityDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *float turbidity = 2;
   *float tds = 3;
   *float temperature = 4;
   * </pre>
   *
   * <code>float ph = 1;</code>
   */
  float getPh();
}
